name: Deploy Hugo Site to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build the Hugo site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        run: |
          # Configure Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Initialize the gh-pages branch
          git fetch origin gh-pages
          git checkout gh-pages || git checkout --orphan gh-pages

          # Remove existing files in gh-pages
          git rm -rf .

          # Copy the contents of public/ to the root of gh-pages
          cp -r ../public/* .

          # Add and commit changes
          git add .
          git commit -m "Deploy Hugo site via GitHub Actions"

          # Push changes to gh-pages branch
          git push origin gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
